site_name: "Numerical methods, data science and statistics for physical sciences"
theme: readthedocs
theme_dir: 'readthedocs_custom'
edit_uri: edit/master/docs/
repo_url: https://github.com/bccp/seljak-computational-physics-2017
extra:
  logo : img/banner.png
  logo_name : true
